### ISSUE TITLE
Wrong `content-type` is set for `acquireAccessToken`

### ISSUE THREAD

**Issue by karimStekelenburg** [Sphereon-Opensource/OpenID4VCI-client#18]
I came across an issue when trying to acquire the access token (by running `OpenID4VCIClient.acquireAccessToken()`).

I'm currently testing my setup against [MATTR's launchpad](https://launchpad.mattrlabs.com/). When I try to run `OpenID4VCIClient.acquireAccessToken()`, I'm getting a `400` response code with the following error message: `only application/x-www-form-urlencoded content-type bodies are supported on POST /token`.

After monitoring my outbound traffic I found that `content-type` was set to `text/plain;charset=UTF-8`. When I intercept the outgoing request and change the `content-type` to `application/x-www-form-urlencoded` the request succeeds and everything works as expected.

After some debugging, I can't seem to find the problem in this codebase. [HttpUtils.formPost](https://github.com/Sphereon-Opensource/OpenID4VCI-client/blob/d7491baf298ff53f38eb586ab931decb67b3780d/lib/functions/HttpUtils.ts#L15) seems to set the `content-type` correctly... I'm not sure, but it could be an issue with `cross-fetch`.

I will continue looking into this but wanted to post it here in case anyone else runs into the same problem.

Love the API and solid typing by the way, nice job! 🚀

**Comment by karimStekelenburg** [comment]
Small update, when I log the request headers in `node-fetch` I get an empty array.

**Comment by nklomp** [comment]
Hi @karimStekelenburg Hmzz, our wallet is working fine using the same version of the lib. What I do believe is going on is that you haven't toggled the 'authentication required' toggle and selected a user. Please note that current library only implements the PreAuthorized Code flow of the spec. It isn't too much work to implement the full spec, but we currently have a few projects getting in the way of finishing that.

If the above isn't it, could you give us some environment details?

**Comment by karimStekelenburg** [comment]
Hi @nklomp! I'm aware that only pre-auth is supported. I will be happy to contribute to the auth flow :)

As for this issue, after some digging I found the problem. I just opened a PR that fixes it!

**Comment by nklomp** [comment]
Thanks for the PR. Merged and release will follow later tonight.

**Comment by nklomp** [comment]
@karimStekelenburg [0.3.5](https://www.npmjs.com/package/@sphereon/openid4vci-client) has been released, with your fix in it. Thanks again
