### ISSUE TITLE
'isValidURL' returns false on valid URL

### ISSUE THREAD

**Issue by honungsburk** [Sphereon-Opensource/OpenID4VCI-client#23]
**What I expect to happen**
`isValidURL` should return true on the URL "http:localhost:4000/some/random/path"

**What actually happens**
It returns false.

**Comment by nklomp** [comment]
We will have to test it. But be aware that the spec requires htrps connections, so probably that is the reason for it.

**Comment by nklomp** [comment]
Of course we can make an exception for localhost if the above is the reason for it.

**Comment by nklomp** [comment]
Oh, overlooked something, which I now see when generating some test cases. Your example really isn't a valid url. The scheme should be `http://` not just `http:`. Will add some testcases to verify.

The regex does allow for non-https sheme's already it seems

**Comment by nklomp** [comment]
Okay looking at the regex, it does go wrong even if the scheme is correctly applied. That has to do with the regex either accepting an IPV4 address (so 127.0.0.1 would have worked) or a hostname with a domain. So it required at least one dot in the hostname. Obviously the hostname 'localhost' doesn't have that. Have adjusted the regex and will add some more test cases. A new release with the fix will follow shortly
